close all;
clear;
clc;
load("hw1_2\MIT6_057IAP19_hw2\optionalData.mat");
smoothed2 = nonUniformRectFilter(x, 2);
smoothed1 = nonUniformRectFilter(x, 1);
smoothed_interp2 = nonUniformRectFilterWithInterp(x, 2);
smoothed_interp1 = nonUniformRectFilterWithInterp(x, 1);
figure;
plot(x(:, 1), x(:, 2), 'bo');
hold on;
plot(smoothed2(:, 1), smoothed2(:, 2), LineWidth=2);
hold on;
plot(smoothed1(:, 1), smoothed1(:, 2), LineWidth=2);
hold on;
plot(smoothed_interp2(:, 1), smoothed_interp2(:, 2), LineWidth=2);
hold on;
plot(smoothed_interp1(:, 1), smoothed_interp1(:, 2), LineWidth=2);
hold on;
title('Smoothing Illustration, nonuniform spacing');
xlabel('X Value');
ylabel('Y Value');
legend('Original Data', 'Smoothed window 2 without Interp', 'Smoothed window 1 without Interp', 'Smoothed window 2 with Interp', 'Smoothed window 1 with Interp');