function face_edge_set = create_face_edge_set(vertex, face)
face_set = create_face_set(vertex, face);
face_edge_set = cat(3, ...
    squeeze(face_set(:,2,:) - face_set(:,1,:)), ...
    squeeze(face_set(:,3,:) - face_set(:,2,:)), ...
    squeeze(face_set(:,1,:) - face_set(:,3,:)) ...
);
end